# Generated by Django 5.0.7 on 2024-08-29 13:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('so_dien_thoai', models.CharField(max_length=15)),
                ('dia_chi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PhanLoai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('mo_ta', models.TextField()),
                ('gioi_tinh', models.CharField(max_length=50)),
                ('mau_sac', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('so_dien_thoai', models.CharField(max_length=15)),
                ('dia_chi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('mo_ta', models.TextField()),
                ('gia_goc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gia_sale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('so_luong', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('so_luong_ban', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('phan_loai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='san_phams', to='home.phanloai')),
            ],
        ),
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tong_tien', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ngay_dat', models.DateField()),
                ('khach_hangs', models.ManyToManyField(related_name='don_hangs', to='home.khachhang')),
                ('san_phams', models.ManyToManyField(related_name='don_hangs', to='home.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diem', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('binh_luan', models.TextField(blank=True, null=True)),
                ('ngay_danh_gia', models.DateField(auto_now_add=True)),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_gias', to='home.khachhang')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_gias', to='home.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='GiaoHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_giao', models.DateField()),
                ('trang_thai_don_hang', models.CharField(max_length=50)),
                ('don_hang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='giao_hang', to='home.donhang')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giao_hangs', to='home.shipper')),
            ],
        ),
    ]
