# Generated by Django 5.0.7 on 2024-08-31 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='danhgia',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to='danhgia_images/'),
        ),
        migrations.CreateModel(
            name='HinhAnhSanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinh_anh', models.ImageField(upload_to='sanpham_images/')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hinh_anh', to='home.sanpham')),
            ],
        ),
    ]
